[package]
name = "vmin_machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "vmin_machine"
path = "src/lib.rs"

[dependencies]
enum-repr = "0.2.6"
